version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: foodflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Zaman@501
      MYSQL_DATABASE: foodflow
    ports:
      - "3306:3306"
    volumes:
      - foodflow-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: foodflow-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foodflow
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Zaman@501
    ports:
      - "8087:8087"

  prometheus:
    image: prom/prometheus:latest
    container_name: foodflow-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: foodflow-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

volumes:
  foodflow-mysql-data:
